"""Native group-level analysis foundations."""

from __future__ import annotations

from ._examine_control import (
    ExaminationControl,
    GeometryControl,
    InfluenceReview,
    QualityRule,
    SurpriseReview,
    examination_control,
)
from ._examine_geometry import geometry_projection
from .adapters import GroupAdapter, GroupProbe
from .collect import collect_results
from .dataset import (
    GroupDataset,
    group_dataset,
    group_dataset_from_group_data,
    register_core_adapters,
)
from .dtypes import (
    GROUP_FLOAT_DTYPE,
    GROUP_INDEX_DTYPE,
    as_group_float_array,
    as_group_index_array,
)
from .errors import (
    AdapterContractError,
    GroupAnalysisError,
    GroupConfigError,
    GroupReducerError,
    GroupRegistryError,
    GroupSchemaError,
    GroupSpaceError,
    UnsupportedGroupFeatureError,
)
from .examine import GroupExamination, ResidualEmbedding, examine_group, examine_reduced
from .io import GDS_H5_VERSION, read_hdf5, write_hdf5
from .ops import (
    derive,
    mask,
    posthoc,
    posthoc_bh,
    posthoc_by,
    reduce,
    register_core_posthoc,
    subset,
    write_out,
)
from .progress import (
    GroupProgressEvent,
    ProgressCallback,
    ProgressReporter,
    emit_progress,
)
from .reducers import (
    GroupLinearModel,
    combine_fisher,
    combine_lancaster,
    combine_stouffer,
    group_model,
    lmm_ri,
    lmm_ri_slope1,
    lmm_unavailable,
    meta_fe,
    meta_fe_reg,
    meta_re,
    meta_re_reg,
    ols_voxelwise,
    perm_onesample,
    perm_twosample,
    register_core_reducers,
)
from .registry import (
    GroupRegistry,
    RegistryEntry,
    adapter_registry,
    map_family_registry,
    posthoc_registry,
    reducer_registry,
)
from .space import (
    BasisSpace,
    GroupSpace,
    ParcelSpace,
    SampleLabelSpace,
    SurfaceSpace,
    VoxelSpace,
    assert_compatible_spaces,
    common_mask,
)
from .typed import GroupLmResult, fmri_group_lm

__all__ = [
    "AdapterContractError",
    "BasisSpace",
    "GROUP_FLOAT_DTYPE",
    "GROUP_INDEX_DTYPE",
    "GDS_H5_VERSION",
    "GroupAnalysisError",
    "GroupAdapter",
    "GroupConfigError",
    "GroupDataset",
    "GroupProbe",
    "GroupProgressEvent",
    "GroupLinearModel",
    "GroupReducerError",
    "GroupRegistry",
    "GroupRegistryError",
    "GroupSchemaError",
    "GroupSpace",
    "GroupSpaceError",
    "ParcelSpace",
    "ProgressCallback",
    "ProgressReporter",
    "RegistryEntry",
    "SampleLabelSpace",
    "SurfaceSpace",
    "UnsupportedGroupFeatureError",
    "VoxelSpace",
    "ExaminationControl",
    "GeometryControl",
    "GroupExamination",
    "GroupLmResult",
    "InfluenceReview",
    "QualityRule",
    "ResidualEmbedding",
    "SurpriseReview",
    "collect_results",
    "examination_control",
    "examine_group",
    "examine_reduced",
    "fmri_group_lm",
    "geometry_projection",
    "adapter_registry",
    "as_group_float_array",
    "as_group_index_array",
    "assert_compatible_spaces",
    "common_mask",
    "combine_fisher",
    "combine_lancaster",
    "combine_stouffer",
    "derive",
    "emit_progress",
    "group_dataset",
    "group_dataset_from_group_data",
    "group_model",
    "lmm_ri",
    "lmm_ri_slope1",
    "lmm_unavailable",
    "mask",
    "map_family_registry",
    "meta_fe",
    "meta_fe_reg",
    "meta_re",
    "meta_re_reg",
    "ols_voxelwise",
    "perm_onesample",
    "perm_twosample",
    "posthoc_registry",
    "posthoc",
    "posthoc_bh",
    "posthoc_by",
    "reduce",
    "reducer_registry",
    "register_core_adapters",
    "register_core_posthoc",
    "register_core_reducers",
    "read_hdf5",
    "subset",
    "write_out",
    "write_hdf5",
]
