"""Native group-level analysis foundations."""

from __future__ import annotations

from .adapters import GroupAdapter, GroupProbe
from .dataset import GroupDataset, group_dataset, group_dataset_from_group_data
from .dtypes import (
    GROUP_FLOAT_DTYPE,
    GROUP_INDEX_DTYPE,
    as_group_float_array,
    as_group_index_array,
)
from .errors import (
    AdapterContractError,
    GroupAnalysisError,
    GroupConfigError,
    GroupReducerError,
    GroupRegistryError,
    GroupSchemaError,
    GroupSpaceError,
    UnsupportedGroupFeatureError,
)
from .io import GDS_H5_VERSION, read_hdf5, write_hdf5
from .ops import derive, mask, posthoc, reduce, subset, write_out
from .progress import (
    GroupProgressEvent,
    ProgressCallback,
    ProgressReporter,
    emit_progress,
)
from .reducers import (
    combine_fisher,
    combine_lancaster,
    combine_stouffer,
    lmm_ri,
    lmm_ri_slope1,
    lmm_unavailable,
    meta_fe,
    meta_fe_reg,
    meta_re,
    meta_re_reg,
    ols_voxelwise,
    perm_onesample,
    perm_twosample,
    register_core_reducers,
)
from .registry import (
    GroupRegistry,
    RegistryEntry,
    adapter_registry,
    map_family_registry,
    posthoc_registry,
    reducer_registry,
)
from .space import (
    BasisSpace,
    GroupSpace,
    ParcelSpace,
    SampleLabelSpace,
    SurfaceSpace,
    VoxelSpace,
    assert_compatible_spaces,
    common_mask,
)

__all__ = [
    "AdapterContractError",
    "BasisSpace",
    "GROUP_FLOAT_DTYPE",
    "GROUP_INDEX_DTYPE",
    "GDS_H5_VERSION",
    "GroupAnalysisError",
    "GroupAdapter",
    "GroupConfigError",
    "GroupDataset",
    "GroupProbe",
    "GroupProgressEvent",
    "GroupReducerError",
    "GroupRegistry",
    "GroupRegistryError",
    "GroupSchemaError",
    "GroupSpace",
    "GroupSpaceError",
    "ParcelSpace",
    "ProgressCallback",
    "ProgressReporter",
    "RegistryEntry",
    "SampleLabelSpace",
    "SurfaceSpace",
    "UnsupportedGroupFeatureError",
    "VoxelSpace",
    "adapter_registry",
    "as_group_float_array",
    "as_group_index_array",
    "assert_compatible_spaces",
    "common_mask",
    "combine_fisher",
    "combine_lancaster",
    "combine_stouffer",
    "derive",
    "emit_progress",
    "group_dataset",
    "group_dataset_from_group_data",
    "lmm_ri",
    "lmm_ri_slope1",
    "lmm_unavailable",
    "mask",
    "map_family_registry",
    "meta_fe",
    "meta_fe_reg",
    "meta_re",
    "meta_re_reg",
    "ols_voxelwise",
    "perm_onesample",
    "perm_twosample",
    "posthoc_registry",
    "posthoc",
    "reduce",
    "reducer_registry",
    "register_core_reducers",
    "read_hdf5",
    "subset",
    "write_out",
    "write_hdf5",
]
