"""Reduced-rank regression primitives for fMRI GLMs."""

from __future__ import annotations

from dataclasses import dataclass, replace
from typing import Literal, Optional, Sequence, cast

import numpy as np
from numpy.typing import NDArray

from ..glm.solver import fast_preproject

RankMode = Literal["fixed", "energy", "rss_budget"]
ReducedRankSEMode = Literal["conditional", "bootstrap"]


@dataclass(frozen=True)
class ReducedRankConfig:
    """Configuration for reduced-rank regression.

    The rank constraint is applied to the fitted signal generated by the
    target columns. Non-target columns are treated as nuisance regressors and
    refit without a rank constraint.
    """

    rank: Optional[int] = None
    rank_mode: RankMode = "fixed"
    energy_keep: float = 0.99
    rss_budget: Optional[float] = None
    ridge: float = 0.0
    se_mode: ReducedRankSEMode = "conditional"
    bootstrap_n: int = 200
    bootstrap_block_size: int = 1
    bootstrap_seed: Optional[int] = None

    def __post_init__(self) -> None:
        if self.rank_mode not in ("fixed", "energy", "rss_budget"):
            raise ValueError("rank_mode must be 'fixed', 'energy', or 'rss_budget'")
        if self.rank is not None and (
            isinstance(self.rank, bool)
            or not isinstance(self.rank, int)
            or self.rank < 1
        ):
            raise ValueError("rank must be a positive integer or None")
        if not (0.0 < float(self.energy_keep) <= 1.0):
            raise ValueError("energy_keep must be in (0, 1]")
        if self.rank_mode == "rss_budget" and self.rss_budget is None:
            raise ValueError("rss_budget is required when rank_mode='rss_budget'")
        if self.rss_budget is not None and float(self.rss_budget) < 0:
            raise ValueError("rss_budget must be non-negative")
        if float(self.ridge) < 0:
            raise ValueError("ridge must be >= 0")
        if self.se_mode not in ("conditional", "bootstrap"):
            raise ValueError("se_mode must be 'conditional' or 'bootstrap'")
        if (
            isinstance(self.bootstrap_n, bool)
            or not isinstance(self.bootstrap_n, int)
            or self.bootstrap_n < 1
        ):
            raise ValueError("bootstrap_n must be a positive integer")
        if self.se_mode == "bootstrap" and self.bootstrap_n < 2:
            raise ValueError("bootstrap_n must be at least 2 when se_mode='bootstrap'")
        if (
            isinstance(self.bootstrap_block_size, bool)
            or not isinstance(self.bootstrap_block_size, int)
            or self.bootstrap_block_size < 1
        ):
            raise ValueError("bootstrap_block_size must be a positive integer")
        if self.bootstrap_seed is not None and (
            isinstance(self.bootstrap_seed, bool)
            or not isinstance(self.bootstrap_seed, int)
        ):
            raise ValueError("bootstrap_seed must be an integer or None")


@dataclass(frozen=True)
class ReducedRankResult:
    """Result from :func:`fit_reduced_rank`."""

    betas: NDArray[np.float64]
    rss: NDArray[np.float64]
    sigma2: NDArray[np.float64]
    dfres: float
    rank: int
    model_rank: int
    XtXinv: NDArray[np.float64]
    full_betas: NDArray[np.float64]
    singular_values: NDArray[np.float64]
    target_columns: tuple[int, ...]
    nuisance_columns: tuple[int, ...]
    fitted: Optional[NDArray[np.float64]] = None
    bootstrap_se: Optional[NDArray[np.float64]] = None


@dataclass(frozen=True)
class _PreparedReducedRank:
    X: NDArray[np.float64]
    Y: NDArray[np.float64]
    target_columns: tuple[int, ...]
    nuisance_columns: tuple[int, ...]
    X_target: NDArray[np.float64]
    X_target_resid: NDArray[np.float64]
    target_pinv: NDArray[np.float64]
    nuisance_pinv: Optional[NDArray[np.float64]]
    U: NDArray[np.float64]
    singular_values: NDArray[np.float64]
    Vt: NDArray[np.float64]
    available_rank: int


def fit_reduced_rank(
    X: NDArray[np.float64],
    Y: NDArray[np.float64],
    config: ReducedRankConfig | None = None,
    *,
    target_columns: Sequence[int] | None = None,
    return_fitted: bool = False,
) -> ReducedRankResult:
    """Fit a reduced-rank GLM.

    Parameters
    ----------
    X
        Design matrix with shape ``(n_timepoints, n_columns)``.
    Y
        Response matrix with shape ``(n_timepoints, n_voxels)``.
    config
        Reduced-rank configuration. Defaults to an unrestricted fixed-rank
        solution, which matches ordinary least squares up to numerical error.
    target_columns
        Columns whose fitted signal should be rank-constrained. Columns not in
        this set are nuisance regressors and remain unrestricted. If omitted,
        all columns are constrained.
    return_fitted
        Include ``X @ betas`` in the result.
    """
    rr_config = config or ReducedRankConfig()
    X_arr, Y_arr = _validate_xy(X, Y)
    projection = fast_preproject(X_arr)
    prepared = _prepare_reduced_rank(X_arr, Y_arr, rr_config, target_columns)

    chosen_rank = _choose_rank(prepared, rr_config)
    betas = _assemble_betas(prepared, chosen_rank)
    full_betas = _assemble_betas(prepared, prepared.available_rank)

    fitted = X_arr @ betas
    residuals = Y_arr - fitted
    rss = cast("NDArray[np.float64]", np.sum(residuals**2, axis=0))
    dfres = float(projection.dfres)
    sigma2 = rss / max(dfres, 1.0)

    bootstrap_se = None
    if rr_config.se_mode == "bootstrap":
        bootstrap_se = _bootstrap_se(
            X_arr,
            Y_arr,
            rr_config,
            prepared.target_columns,
            fitted,
            residuals,
        )

    return ReducedRankResult(
        betas=betas,
        rss=rss,
        sigma2=cast("NDArray[np.float64]", sigma2),
        dfres=dfres,
        rank=chosen_rank,
        model_rank=int(projection.rank),
        XtXinv=projection.XtXinv,
        full_betas=full_betas,
        singular_values=prepared.singular_values,
        target_columns=prepared.target_columns,
        nuisance_columns=prepared.nuisance_columns,
        fitted=fitted if return_fitted else None,
        bootstrap_se=bootstrap_se,
    )


def _validate_xy(
    X: NDArray[np.float64],
    Y: NDArray[np.float64],
) -> tuple[NDArray[np.float64], NDArray[np.float64]]:
    X_arr = np.asarray(X, dtype=np.float64)
    Y_arr = np.asarray(Y, dtype=np.float64)
    if Y_arr.ndim == 1:
        Y_arr = Y_arr[:, np.newaxis]
    if X_arr.ndim != 2:
        raise ValueError(f"X must be 2-D, got shape {X_arr.shape}")
    if Y_arr.ndim != 2:
        raise ValueError(f"Y must be 1-D or 2-D, got shape {Y_arr.shape}")
    if X_arr.shape[0] != Y_arr.shape[0]:
        raise ValueError("X and Y must have the same number of rows")
    if X_arr.shape[0] == 0 or X_arr.shape[1] == 0:
        raise ValueError("X must have at least one row and one column")
    if not np.all(np.isfinite(X_arr)):
        raise ValueError("Design matrix contains NA/Inf values")
    if not np.all(np.isfinite(Y_arr)):
        raise ValueError("Response matrix contains NA/Inf values")
    return X_arr, Y_arr


def _normalize_target_columns(
    target_columns: Sequence[int] | None,
    n_columns: int,
) -> tuple[int, ...]:
    if target_columns is None:
        return tuple(range(n_columns))
    out: list[int] = []
    for value in target_columns:
        if isinstance(value, bool) or not isinstance(value, int):
            raise TypeError("target_columns must contain integer column indices")
        idx = int(value)
        if idx < 0 or idx >= n_columns:
            raise IndexError(f"target column index {idx} is out of range")
        out.append(idx)
    if not out:
        raise ValueError("target_columns must contain at least one column")
    if len(set(out)) != len(out):
        raise ValueError("target_columns must not contain duplicates")
    return tuple(out)


def _regularized_pinv(
    X: NDArray[np.float64],
    ridge: float,
) -> NDArray[np.float64]:
    if X.shape[1] == 0:
        return np.zeros((0, X.shape[0]), dtype=np.float64)
    if ridge == 0:
        return cast("NDArray[np.float64]", np.linalg.pinv(X))
    gram = X.T @ X + float(ridge) * np.eye(X.shape[1])
    try:
        return cast("NDArray[np.float64]", np.linalg.solve(gram, X.T))
    except np.linalg.LinAlgError:
        return cast("NDArray[np.float64]", np.linalg.pinv(gram) @ X.T)


def _prepare_reduced_rank(
    X: NDArray[np.float64],
    Y: NDArray[np.float64],
    config: ReducedRankConfig,
    target_columns: Sequence[int] | None,
) -> _PreparedReducedRank:
    n_columns = X.shape[1]
    target = _normalize_target_columns(target_columns, n_columns)
    nuisance = tuple(i for i in range(n_columns) if i not in set(target))
    X_target = X[:, target]

    if nuisance:
        X_nuisance = X[:, nuisance]
        nuisance_pinv = _regularized_pinv(X_nuisance, config.ridge)
        Y_resid = Y - X_nuisance @ (nuisance_pinv @ Y)
        X_target_resid = X_target - X_nuisance @ (nuisance_pinv @ X_target)
    else:
        nuisance_pinv = None
        Y_resid = Y
        X_target_resid = X_target

    target_pinv = _regularized_pinv(X_target_resid, config.ridge)
    task_fitted = X_target_resid @ (target_pinv @ Y_resid)
    U, singular_values, Vt = np.linalg.svd(task_fitted, full_matrices=False)
    available_rank = _numerical_rank(singular_values, *task_fitted.shape)

    return _PreparedReducedRank(
        X=X,
        Y=Y,
        target_columns=target,
        nuisance_columns=nuisance,
        X_target=X_target,
        X_target_resid=X_target_resid,
        target_pinv=target_pinv,
        nuisance_pinv=nuisance_pinv,
        U=cast("NDArray[np.float64]", U),
        singular_values=cast("NDArray[np.float64]", singular_values),
        Vt=cast("NDArray[np.float64]", Vt),
        available_rank=available_rank,
    )


def _numerical_rank(
    singular_values: NDArray[np.float64],
    n_rows: int,
    n_cols: int,
) -> int:
    if singular_values.size == 0:
        return 0
    tol = max(n_rows, n_cols) * np.finfo(np.float64).eps * singular_values[0]
    return int(np.sum(singular_values > tol))


def _choose_rank(
    prepared: _PreparedReducedRank,
    config: ReducedRankConfig,
) -> int:
    max_rank = prepared.available_rank
    if max_rank == 0:
        return 0

    if config.rank_mode == "fixed":
        requested = max_rank if config.rank is None else int(config.rank)
        return min(requested, max_rank)

    if config.rank_mode == "energy":
        energy = prepared.singular_values[:max_rank] ** 2
        total = float(np.sum(energy))
        if total <= 0:
            return 0
        cumulative = np.cumsum(energy) / total
        return int(np.searchsorted(cumulative, float(config.energy_keep)) + 1)

    full_betas = _assemble_betas(prepared, max_rank)
    full_rss = _total_rss(prepared.X, prepared.Y, full_betas)
    budget = float(cast(float, config.rss_budget))
    for rank in range(0, max_rank + 1):
        betas = _assemble_betas(prepared, rank)
        if _total_rss(prepared.X, prepared.Y, betas) - full_rss <= budget:
            return rank
    return max_rank


def _assemble_betas(
    prepared: _PreparedReducedRank,
    rank: int,
) -> NDArray[np.float64]:
    rank = min(max(int(rank), 0), prepared.available_rank)
    n_columns = prepared.X.shape[1]
    n_voxels = prepared.Y.shape[1]
    betas = np.zeros((n_columns, n_voxels), dtype=np.float64)

    if rank == 0:
        task_fitted = np.zeros_like(prepared.Y)
    else:
        task_fitted = (
            prepared.U[:, :rank] * prepared.singular_values[np.newaxis, :rank]
        ) @ prepared.Vt[:rank, :]

    target_betas = prepared.target_pinv @ task_fitted
    betas[list(prepared.target_columns), :] = target_betas

    if prepared.nuisance_columns:
        assert prepared.nuisance_pinv is not None
        nuisance_response = prepared.Y - prepared.X_target @ target_betas
        nuisance_betas = prepared.nuisance_pinv @ nuisance_response
        betas[list(prepared.nuisance_columns), :] = nuisance_betas

    return cast("NDArray[np.float64]", betas)


def _total_rss(
    X: NDArray[np.float64],
    Y: NDArray[np.float64],
    betas: NDArray[np.float64],
) -> float:
    residuals = Y - X @ betas
    return float(np.sum(residuals**2))


def _bootstrap_se(
    X: NDArray[np.float64],
    Y: NDArray[np.float64],
    config: ReducedRankConfig,
    target_columns: tuple[int, ...],
    fitted: NDArray[np.float64],
    residuals: NDArray[np.float64],
) -> NDArray[np.float64]:
    rng = np.random.default_rng(config.bootstrap_seed)
    bootstrap_config = replace(config, se_mode="conditional")
    draws = np.empty((config.bootstrap_n, X.shape[1], Y.shape[1]), dtype=np.float64)
    for draw in range(config.bootstrap_n):
        idx = _block_bootstrap_indices(
            X.shape[0],
            config.bootstrap_block_size,
            rng,
        )
        Y_star = fitted + residuals[idx, :]
        draws[draw] = fit_reduced_rank(
            X,
            Y_star,
            bootstrap_config,
            target_columns=target_columns,
        ).betas
    return cast("NDArray[np.float64]", np.std(draws, axis=0, ddof=1))


def _block_bootstrap_indices(
    n: int,
    block_size: int,
    rng: np.random.Generator,
) -> NDArray[np.intp]:
    if block_size <= 1:
        return cast("NDArray[np.intp]", rng.integers(0, n, size=n, dtype=np.intp))
    # fmrireg 0.2.0: a block that covers the whole series is one contiguous
    # identity draw, not a modular rotation of a random start.
    if block_size >= n:
        return np.arange(n, dtype=np.intp)
    n_blocks = int(np.ceil(n / block_size))
    starts = rng.integers(0, n, size=n_blocks, dtype=np.intp)
    offsets = np.arange(block_size, dtype=np.intp)
    blocks = (starts[:, np.newaxis] + offsets[np.newaxis, :]) % n
    return cast("NDArray[np.intp]", blocks.ravel()[:n])
