"""Tests for numerical parity between R fmridesign and Python pyfmridesign.

Each test loads a JSON fixture generated by generate_fixtures.R and compares
the Python output against R golden reference values.

Fixtures are generated by running: Rscript tests/generate_fixtures.R

SPM canonical alignment (early 2026) intentionally diverged fmrimod's
default ``basis="spm"`` HRF from the R ``fmrireg`` parameterization to
match SPM ``spm_hrf`` and Nilearn ``_gamma_difference_hrf``. Until the
R-side fixtures are regenerated against an R fmrireg that adopts the
SPM standard parameterization (tracked in the bbuchsbaum/fmrihrf
issue queue alongside the dispersion-derivative fix), R parity tests
that pin SPMG-realised values are marked ``xfail(strict=True)``. The
legacy R parameterization stays available via ``basis="spm_legacy"``
and can be substituted into these tests for full R parity if needed.
"""

import json
from pathlib import Path

import numpy as np
import pandas as pd
import pytest

FIXTURE_DIR = Path(__file__).parent / "fixtures"
ATOL = 1e-6  # absolute tolerance for numeric comparisons


def load_fixture(name: str) -> dict:
    """Load a JSON fixture file."""
    path = FIXTURE_DIR / f"{name}.json"
    if not path.exists():
        pytest.skip(f"Fixture {name}.json not found; run generate_fixtures.R first")
    with open(path) as f:
        return json.load(f)


def _make_sampling_frame(sf_info):
    """Create a SamplingFrame from fixture sampling_frame info."""
    from fmrimod import SamplingFrame
    blocklens = sf_info["blocklens"]
    if not isinstance(blocklens, list):
        blocklens = [blocklens]
    return SamplingFrame(blocklens=blocklens, TR=sf_info["TR"])


def _events_to_df(events) -> pd.DataFrame:
    """Convert fixture events (list of dicts or dict of lists) to DataFrame."""
    return pd.DataFrame(events)


# ============================================================================
# Fixture 1: Simple HRF convolution (spmg1)
# ============================================================================
class TestSimpleHRF:
    """Test spmg1 HRF convolution with 2 conditions."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_simple_hrf")

    def test_design_matrix_shape(self):
        r_dm = np.array(self.fix["design_matrix"]["matrix"])
        assert r_dm.shape == (
            self.fix["design_matrix"]["nrow"],
            self.fix["design_matrix"]["ncol"],
        )

    @pytest.mark.xfail(
        reason=(
            "fmrimod's default SPM canonical was realigned to SPM/Nilearn "
            "standard parameterization (early 2026); the R fixture pins "
            "the legacy R-fmrireg shape. Tracking issue on "
            "bbuchsbaum/fmrihrf will bring R into alignment; until then "
            "this test can be flipped to basis='spm_legacy' for R parity."
        ),
        strict=True,
    )
    def test_design_matrix_values(self):
        from fmrimod import event_model, design_matrix

        df = _events_to_df(self.fix["events"])
        sf = _make_sampling_frame(self.fix["sampling_frame"])

        model = event_model(
            "onset ~ hrf(condition, basis='spmg1')",
            data=df,
            block="run",
            sampling_frame=sf,
            durations=self.fix["model_info"]["durations"],
            precision=self.fix["model_info"]["precision"],
        )

        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["design_matrix"]["matrix"])

        assert py_dm.shape == r_dm.shape, (
            f"Shape mismatch: Python {py_dm.shape} vs R {r_dm.shape}"
        )
        np.testing.assert_allclose(py_dm, r_dm, atol=ATOL,
                                   err_msg="spmg1 design matrix mismatch")

    def test_column_names(self):
        from fmrimod import event_model

        df = _events_to_df(self.fix["events"])
        sf = _make_sampling_frame(self.fix["sampling_frame"])

        model = event_model(
            "onset ~ hrf(condition, basis='spmg1')",
            data=df,
            block="run",
            sampling_frame=sf,
            durations=self.fix["model_info"]["durations"],
            precision=self.fix["model_info"]["precision"],
        )

        r_colnames = self.fix["design_matrix"]["colnames"]
        py_colnames = list(model.column_names)
        assert py_colnames == r_colnames, (
            f"Column names mismatch:\n  Python: {py_colnames}\n  R: {r_colnames}"
        )


# ============================================================================
# Fixture 2: HRF with temporal derivative (spmg2)
# ============================================================================
class TestSPMG2:
    """Test spmg2 HRF (canonical + temporal derivative)."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_spmg2")

    def test_design_matrix_ncol(self):
        r_dm = np.array(self.fix["design_matrix"]["matrix"])
        expected_ncol = self.fix["model_info"]["nbasis"] * self.fix["model_info"]["n_conditions"]
        assert r_dm.shape[1] == expected_ncol

    @pytest.mark.xfail(
        reason=(
            "fmrimod's default SPM canonical was realigned to SPM/Nilearn "
            "standard parameterization (early 2026); the R fixture pins "
            "the legacy R-fmrireg shape. Tracking issue on "
            "bbuchsbaum/fmrihrf will bring R into alignment; until then "
            "this test can be flipped to basis='spm_legacy' for R parity."
        ),
        strict=True,
    )
    def test_design_matrix_values(self):
        from fmrimod import event_model, design_matrix

        df = _events_to_df(self.fix["events"])
        sf = _make_sampling_frame(self.fix["sampling_frame"])

        model = event_model(
            "onset ~ hrf(condition, basis='spmg2')",
            data=df,
            block="run",
            sampling_frame=sf,
            durations=self.fix["model_info"]["durations"],
            precision=self.fix["model_info"]["precision"],
        )

        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["design_matrix"]["matrix"])

        assert py_dm.shape == r_dm.shape, (
            f"Shape mismatch: Python {py_dm.shape} vs R {r_dm.shape}"
        )
        np.testing.assert_allclose(py_dm, r_dm, atol=ATOL,
                                   err_msg="spmg2 design matrix mismatch")


# ============================================================================
# Fixture 3: Multi-block design
# ============================================================================
class TestMultiBlock:
    """Test multi-block design: HRF isolation across blocks."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_multiblock")

    @pytest.mark.xfail(
        reason=(
            "fmrimod's default SPM canonical was realigned to SPM/Nilearn "
            "standard parameterization (early 2026); the R fixture pins "
            "the legacy R-fmrireg shape. Tracking issue on "
            "bbuchsbaum/fmrihrf will bring R into alignment; until then "
            "this test can be flipped to basis='spm_legacy' for R parity."
        ),
        strict=True,
    )
    def test_full_design_matrix(self):
        from fmrimod import event_model, design_matrix

        df = _events_to_df(self.fix["events"])
        sf = _make_sampling_frame(self.fix["sampling_frame"])

        model = event_model(
            "onset ~ hrf(condition, basis='spmg1')",
            data=df,
            block="run",
            sampling_frame=sf,
            precision=0.3,
        )

        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["design_matrix"]["matrix"])

        assert py_dm.shape == r_dm.shape
        np.testing.assert_allclose(py_dm, r_dm, atol=ATOL,
                                   err_msg="Multi-block design matrix mismatch")

    def test_block_isolation(self):
        """Verify per-block matrices from R match corresponding rows."""
        r_dm = np.array(self.fix["design_matrix"]["matrix"])
        n_block1 = self.fix["sampling_frame"]["blocklens"][0]

        block1 = r_dm[:n_block1, :]
        block2 = r_dm[n_block1:, :]

        if "block1_matrix" in self.fix:
            r_block1 = np.array(self.fix["block1_matrix"]["matrix"])
            np.testing.assert_allclose(block1, r_block1, atol=ATOL)
        if "block2_matrix" in self.fix:
            r_block2 = np.array(self.fix["block2_matrix"]["matrix"])
            np.testing.assert_allclose(block2, r_block2, atol=ATOL)


# ============================================================================
# Fixture 4: Contrast weights
# ============================================================================
class TestContrastWeights:
    """Test unit and pair contrast weight computation."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_contrasts")

    def test_contrast_weights_present(self):
        assert "contrasts" in self.fix
        assert len(self.fix["contrasts"]) > 0

    def test_unit_contrast_sums_to_one(self):
        """Unit contrast weight vector should sum to 1."""
        contrasts = self.fix["contrasts"]
        for key, cw in contrasts.items():
            if cw["name"] == "unit_A":
                weights = np.array(cw["weights"])
                assert abs(np.sum(weights) - 1.0) < ATOL, (
                    f"Unit contrast weights sum to {np.sum(weights)}, expected 1"
                )
                return
        pytest.skip("unit_A contrast not found in fixture")

    def test_pair_contrast_sums_to_zero(self):
        """Pair contrast weight vector should sum to 0."""
        contrasts = self.fix["contrasts"]
        for key, cw in contrasts.items():
            if cw["name"] == "pair_AB":
                weights = np.array(cw["weights"])
                assert abs(np.sum(weights)) < ATOL, (
                    f"Pair contrast weights sum to {np.sum(weights)}, expected 0"
                )
                return
        pytest.skip("pair_AB contrast not found in fixture")


# ============================================================================
# Fixture 5: Poly contrast
# ============================================================================
class TestPolyContrast:
    """Test polynomial contrast weights for 4-condition model."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_poly_contrast")

    def test_poly_contrasts_present(self):
        assert "contrasts" in self.fix
        assert len(self.fix["contrasts"]) > 0

    def test_linear_contrast_sums_to_zero(self):
        """Linear poly contrast should sum to 0."""
        contrasts = self.fix["contrasts"]
        for key, cw in contrasts.items():
            if cw["name"] == "poly_linear":
                weights = np.array(cw["weights"])
                assert abs(np.sum(weights)) < ATOL
                return
        pytest.skip("poly_linear contrast not found")


# ============================================================================
# Fixture 7: F-contrasts
# ============================================================================
class TestFContrasts:
    """Test F-contrast weight matrices."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_fcontrasts")

    def test_fcontrasts_present(self):
        assert "fcontrasts" in self.fix
        assert len(self.fix["fcontrasts"]) > 0

    def test_fcontrast_matrix_shape(self):
        """F-contrast matrices should have correct dimensions."""
        for key, fc in self.fix["fcontrasts"].items():
            mat = np.array(fc["matrix"])
            assert mat.shape == (fc["nrow"], fc["ncol"]), (
                f"F-contrast {key} shape mismatch: {mat.shape} vs ({fc['nrow']}, {fc['ncol']})"
            )


# ============================================================================
# Fixture 8: Basis functions
# ============================================================================
class TestBasisFunctions:
    """Test Poly, BSpline, Scale, RobustScale basis functions."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_basis_functions")

    def test_poly_basis(self):
        from fmrimod import Poly

        x = np.array(self.fix["x"])
        r_mat = np.array(self.fix["poly"]["matrix"])

        py_poly = Poly.from_data(x, degree=3)
        py_mat = py_poly.y

        assert py_mat.shape == r_mat.shape, (
            f"Poly shape mismatch: {py_mat.shape} vs {r_mat.shape}"
        )
        # Poly basis may differ by sign (eigenvector sign ambiguity)
        for col in range(r_mat.shape[1]):
            corr = np.corrcoef(py_mat[:, col], r_mat[:, col])[0, 1]
            assert abs(abs(corr) - 1.0) < 1e-4, (
                f"Poly column {col} not correlated: r={corr}"
            )

    def test_scale_basis(self):
        from fmrimod import Scale

        x = np.array(self.fix["x"])
        r_vals = np.array(self.fix["scale"]["values"])

        py_scale = Scale.from_data(x)
        py_vals = np.asarray(py_scale.y).ravel()

        np.testing.assert_allclose(py_vals, r_vals, atol=ATOL,
                                   err_msg="Scale basis mismatch")

    def test_robust_scale_basis(self):
        from fmrimod import RobustScale

        x = np.array(self.fix["x"])
        r_vals = np.array(self.fix["robust_scale"]["values"])

        py_robust = RobustScale.from_data(x)
        py_vals = np.asarray(py_robust.y).ravel()

        np.testing.assert_allclose(py_vals, r_vals, atol=ATOL,
                                   err_msg="RobustScale basis mismatch")


# ============================================================================
# Fixture 9: Baseline model
# ============================================================================
class TestBaselineModel:
    """Test baseline model polynomial drift and DCT basis."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_baseline")

    def test_poly_drift_shape(self):
        r_dm = np.array(self.fix["poly_drift"]["matrix"])
        assert r_dm.shape == (
            self.fix["poly_drift"]["nrow"],
            self.fix["poly_drift"]["ncol"],
        )

    def test_constant_baseline_shape(self):
        r_dm = np.array(self.fix["constant_baseline"]["matrix"])
        assert r_dm.shape == (
            self.fix["constant_baseline"]["nrow"],
            self.fix["constant_baseline"]["ncol"],
        )

    def test_dct_basis_shape(self):
        r_dct = np.array(self.fix["dct_basis"]["matrix"])
        assert r_dct.shape == (
            self.fix["dct_basis"]["nrow"],
            self.fix["dct_basis"]["ncol"],
        )

    def test_poly_drift_values(self):
        from fmrimod import baseline_model, design_matrix

        sf = _make_sampling_frame(self.fix["sampling_frame"])
        model = baseline_model(
            basis="poly",
            degree=int(self.fix["poly_drift"]["degree"]),
            sframe=sf,
        )
        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["poly_drift"]["matrix"])

        assert py_dm.shape == r_dm.shape, (
            f"Shape mismatch: Python {py_dm.shape} vs R {r_dm.shape}"
        )
        np.testing.assert_allclose(py_dm, r_dm, atol=ATOL,
                                   err_msg="Baseline polynomial drift mismatch")

    def test_constant_baseline_values(self):
        from fmrimod import baseline_model, design_matrix

        sf = _make_sampling_frame(self.fix["sampling_frame"])
        model = baseline_model(basis="constant", sframe=sf)
        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["constant_baseline"]["matrix"])

        assert py_dm.shape == r_dm.shape, (
            f"Shape mismatch: Python {py_dm.shape} vs R {r_dm.shape}"
        )
        np.testing.assert_allclose(py_dm, r_dm, atol=ATOL,
                                   err_msg="Constant baseline mismatch")


# ============================================================================
# Fixture 10: Parametric modulation
# ============================================================================
class TestParametricModulation:
    """Test parametric modulation with continuous variable."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_parametric")

    def test_design_matrix_shape(self):
        r_dm = np.array(self.fix["design_matrix"]["matrix"])
        assert r_dm.shape == (
            self.fix["design_matrix"]["nrow"],
            self.fix["design_matrix"]["ncol"],
        )

    @pytest.mark.xfail(
        reason=(
            "fmrimod's default SPM canonical was realigned to SPM/Nilearn "
            "standard parameterization (early 2026); the R fixture pins "
            "the legacy R-fmrireg shape. Tracking issue on "
            "bbuchsbaum/fmrihrf will bring R into alignment; until then "
            "this test can be flipped to basis='spm_legacy' for R parity."
        ),
        strict=True,
    )
    def test_design_matrix_values(self):
        from fmrimod import event_model, design_matrix

        df = _events_to_df(self.fix["events"])
        sf = _make_sampling_frame(self.fix["sampling_frame"])

        model = event_model(
            "onset ~ hrf(condition) + hrf(RT, basis='spmg1')",
            data=df,
            block="run",
            sampling_frame=sf,
            precision=0.3,
        )

        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["design_matrix"]["matrix"])

        assert py_dm.shape == r_dm.shape, (
            f"Shape mismatch: Python {py_dm.shape} vs R {r_dm.shape}"
        )
        np.testing.assert_allclose(py_dm, r_dm, atol=ATOL,
                                   err_msg="Parametric modulation design matrix mismatch")


# ============================================================================
# Fixture 11: Variable durations
# ============================================================================
class TestVariableDurations:
    """Test variable event durations."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_durations")

    @pytest.mark.xfail(
        reason=(
            "fmrimod's default SPM canonical was realigned to SPM/Nilearn "
            "standard parameterization (early 2026); the R fixture pins "
            "the legacy R-fmrireg shape. Tracking issue on "
            "bbuchsbaum/fmrihrf will bring R into alignment; until then "
            "this test can be flipped to basis='spm_legacy' for R parity."
        ),
        strict=True,
    )
    def test_design_matrix_values(self):
        from fmrimod import event_model, design_matrix

        df = _events_to_df(self.fix["events"])
        sf = _make_sampling_frame(self.fix["sampling_frame"])
        durations = self.fix["model_info"]["durations"]

        model = event_model(
            "onset ~ hrf(condition, basis='spmg1')",
            data=df,
            block="run",
            sampling_frame=sf,
            durations=durations,
            precision=0.3,
        )

        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["design_matrix"]["matrix"])

        assert py_dm.shape == r_dm.shape
        np.testing.assert_allclose(py_dm, r_dm, atol=ATOL,
                                   err_msg="Variable duration design matrix mismatch")


# ============================================================================
# Fixture 12: Basis-expanded HRF (spmg3)
# ============================================================================
class TestBasisExpanded:
    """Test basis-expanded HRF with SPMG3."""

    @pytest.fixture(autouse=True)
    def setup(self):
        self.fix = load_fixture("fixture_basis_expanded")

    def test_design_matrix_ncol(self):
        r_dm = np.array(self.fix["design_matrix"]["matrix"])
        expected_ncol = self.fix["model_info"]["nbasis"]  # single condition
        assert r_dm.shape[1] == expected_ncol

    @pytest.mark.xfail(
        reason=(
            "fmrimod's SPMG3 third basis column is the SPM dispersion "
            "derivative (matching SPM and Nilearn). R's "
            "fmrireg::HRF_SPMG3 still uses the second time derivative "
            "in its third column, which is the older R-side definition "
            "we intentionally diverged from. The R fixture was generated "
            "with the second-time-derivative basis and will only match "
            "again once fmrihrf (R) is updated. Tracking issue: see "
            "https://github.com/bbuchsbaum/fmrihrf for the open "
            "ticket to align fmrihrf with the SPM informed-basis "
            "definition. The first two columns (canonical + temporal "
            "derivative) still match R; only the third column diverges."
        ),
        strict=True,
    )
    def test_design_matrix_values(self):
        from fmrimod import event_model, design_matrix

        df = _events_to_df(self.fix["events"])
        sf = _make_sampling_frame(self.fix["sampling_frame"])

        model = event_model(
            "onset ~ hrf(condition, basis='spmg3')",
            data=df,
            block="run",
            sampling_frame=sf,
            precision=0.3,
        )

        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["design_matrix"]["matrix"])

        assert py_dm.shape == r_dm.shape, (
            f"Shape mismatch: Python {py_dm.shape} vs R {r_dm.shape}"
        )
        np.testing.assert_allclose(py_dm, r_dm, atol=ATOL,
                                   err_msg="spmg3 design matrix mismatch")

    @pytest.mark.xfail(
        reason=(
            "fmrimod's default SPM canonical was realigned to SPM/Nilearn "
            "standard parameterization (early 2026); the R fixture pins "
            "the legacy R-fmrireg shape. Tracking issue on "
            "bbuchsbaum/fmrihrf will bring R into alignment; until then "
            "this test can be flipped to basis='spm_legacy' for R parity."
        ),
        strict=True,
    )
    def test_first_two_basis_columns_still_match_r(self):
        """Columns 1-2 (canonical + temporal derivative) must still match R.

        Only the third column (dispersion derivative) diverges from
        R fmrireg; the first two columns are unchanged and should still
        match the R fixture bitwise (within ATOL).
        """
        from fmrimod import event_model, design_matrix

        df = _events_to_df(self.fix["events"])
        sf = _make_sampling_frame(self.fix["sampling_frame"])
        model = event_model(
            "onset ~ hrf(condition, basis='spmg3')",
            data=df, block="run", sampling_frame=sf, precision=0.3,
        )
        py_dm = design_matrix(model)
        r_dm = np.array(self.fix["design_matrix"]["matrix"])
        # SPMG3 has 3 basis columns per condition. With one condition,
        # cols 0/1/2 are canonical/temporal/dispersion. Cols 0-1 should
        # be unchanged from R's output.
        np.testing.assert_allclose(
            py_dm[:, :2], r_dm[:, :2], atol=ATOL,
            err_msg="SPMG3 canonical + temporal-deriv columns must "
            "still match R fmrireg",
        )
